apiVersion: v1alpha1
kind: ServiceLevelObjective
metadata:
  annotations:
    pyrra.dev/dashboard: https://grafana.app-sre.devshift.net/d/92520ea4d6976f30d1618164e186ef9b/mst-stage-slos?orgId=1&refresh=10s&var-datasource=app-sre-stage-01-prometheus&var-namespace={{$labels.namespace}}&var-job=All&var-pod=All&var-interval=5m
    pyrra.dev/message: API Thanos Rule failing to send alerts to Alertmanager and
      is burning too much error budget to guarantee availability SLOs.
    pyrra.dev/runbook: https://github.com/rhobs/configuration/blob/main/docs/sop/observatorium.md#APIAlertmanagerAvailabilityErrorBudgetBurning
  creationTimestamp: null
  labels:
    instance: mst-stage
    service: observatorium-api
  name: api-alerting-availability-slo
spec:
  alerting:
    name: APIAlertmanagerAvailabilityErrorBudgetBurning
  description: API Thanos Rule failing to send alerts to Alertmanager and is burning
    too much error budget to guarantee availability SLOs.
  indicator:
    ratio:
      errors:
        metric: thanos_alert_sender_alerts_dropped_total{container="thanos-rule",
          namespace="observatorium-mst-stage", code=~"^5..$"}
      grouping: null
      total:
        metric: thanos_alert_sender_alerts_dropped_total{container="thanos-rule",
          namespace="observatorium-mst-stage", code!~"^4..$"}
  target: "99"
  window: 28d
status: {}
