apiVersion: v1alpha1
kind: ServiceLevelObjective
metadata:
  annotations:
    pyrra.dev/dashboard: https://grafana.app-sre.devshift.net/d/080e53f245a15445bdf777ae0e66945d/telemeter-staging-slos?orgId=1&refresh=10s&var-datasource=app-sre-stage-01-prometheus&var-namespace={{$labels.namespace}}&var-job=All&var-pod=All&var-interval=5m
    pyrra.dev/message: Telemeter Server /receive is burning too much error budget
      to guarantee availability SLOs.
    pyrra.dev/runbook: https://github.com/rhobs/configuration/blob/main/docs/sop/observatorium.md#TelemeterServerMetricsReceiveWriteAvailabilityErrorBudgetBurning
  creationTimestamp: null
  labels:
    route: telemeter-server-receive
    service: telemeter
  name: rhobs-telemeter-server-metrics-receive-availability-slo
spec:
  alerting:
    name: TelemeterServerMetricsReceiveWriteAvailabilityErrorBudgetBurning
  description: Telemeter Server /receive is burning too much error budget to guarantee
    availability SLOs.
  indicator:
    ratio:
      errors:
        metric: haproxy_server_http_responses_total{route="telemeter-server-metrics-v1-receive",
          code=~"5.."}
      grouping: null
      total:
        metric: haproxy_server_http_responses_total{route="telemeter-server-metrics-v1-receive",
          code!~"^4..$"}
  target: "99"
  window: 28d
status: {}
