apiVersion: v1alpha1
kind: ServiceLevelObjective
metadata:
  annotations:
    pyrra.dev/dashboard: https://grafana.app-sre.devshift.net/d/080e53f245a15445bdf777ae0e66945d/telemeter-staging-slos?orgId=1&refresh=10s&var-datasource=app-sre-stage-01-prometheus&var-namespace={{$labels.namespace}}&var-job=All&var-pod=All&var-interval=5m
    pyrra.dev/message: Telemeter Server /upload is burning too much error budget to
      guarantee latency SLOs.
    pyrra.dev/runbook: https://github.com/rhobs/configuration/blob/main/docs/sop/observatorium.md#TelemeterServerMetricsUploadWriteLatencyErrorBudgetBurning
  creationTimestamp: null
  labels:
    route: telemeter-server-upload
    service: telemeter
  name: rhobs-telemeter-server-metrics-upload-latency-slo
spec:
  alerting:
    name: TelemeterServerMetricsUploadWriteLatencyErrorBudgetBurning
  description: Telemeter Server /upload is burning too much error budget to guarantee
    latency SLOs.
  indicator:
    latency:
      grouping: null
      success:
        metric: http_request_duration_seconds_bucket{job="telemeter-server", handler="upload",
          code=~"^2..$", le="5"}
      total:
        metric: http_request_duration_seconds_count{job="telemeter-server", handler="upload",
          code=~"^2..$"}
  target: "90"
  window: 28d
status: {}
