version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: large
    steps:
    - checkout
    - run:
        name: Check CPU
        command: |
          lscpu
    - run:
        name: Check memory
        command: free -g
    - run:
        name: Install podman
        command: |
          sudo apt-get -y update
          sudo apt-get -y install podman
    - run:
        name: Setup Podman
        command: |
          podman machine init --cpus 4 --memory 16384 --disk-size 80
          podman machine start
    - run:
        name: Check status of podman
        command: |
          podman ps
          podman images
