version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: large
    environment:
      KUBECONFIG: kubeconfig
    steps:
    - checkout
    - run:
        name: Check CPU
        command: |
          lscpu
    - run:
        name: Check memory
        command: free -g
    - run:
        name: Get dependicies
        command: |
          sudo apt-get update
          sudo apt-get install \
            ca-certificates \
            curl \
            wget \
            gnupg \
            lsb-release
          sudo mkdir -m 0755 -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo chmod a+r /etc/apt/keyrings/docker.gpg
          sudo apt-get update
    - run:
        name: Install Docker
        command: sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    - run:
        name: Get docker info
        command: docker info
    - run:
        name: Get OC CLI Binary
        command: |
          wget https://github.com/okd-project/okd/releases/download/4.12.0-0.okd-2023-02-18-033438/openshift-client-linux-4.12.0-0.okd-2023-02-18-033438.tar.gz
          tar xzvf openshift-client-linux-4.12.0-0.okd-2023-02-18-033438.tar.gz
          sudo mv oc kubectl /usr/local/bin
    - run:
        name: Run OC Binary
        command: oc --help
    - run:
        name: Spin up microshift container
        command: |
          docker run -d --name microshift --privileged -v microshift-data:/var/lib -p 6443:6443 -p 80:80 -p 443:443 quay.io/microshift/microshift-aio:latest
          sleep 60
    - run:
        name: Export the kubeconfig
        command: docker exec -i microshift cat /var/lib/microshift/resources/kubeadmin/kubeconfig > tests/kubeconfig
    - run:
        name: List the kubeconfig file
        command: ls tests
    - run:
        name: Deploy the pre-requisites
        command: |
          echo $KUBECONFIG
          cd tests
          oc apply -f pre-requisites-ci.yaml
          ./ci_test.sh
    - run:
        name: Check the pod status
        command: |
          cd tests
          sleep 120
          oc get pods -n minio ; oc get pods -n observatorium ; oc get pods -n observatorium-metrics ; oc get pods -n dex ; oc get pods -n telemeter
          oc get pvc -n observatorium-metrics

