version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: large
    steps:
    - checkout
    - run:
        name: Check CPU
        command: |
          lscpu
    - run:
        name: Check memory
        command: free -g
    - run:
        name: Install podman dependicies
        command: |
          echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
          curl -L "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key" | sudo apt-key add -
    - run:
        name: Install tools
        command: |
          sudo apt update
          sudo apt install qemu-kvm
    - run:
        name: Install podman
        command: |
          sudo wget https://github.com/containers/gvisor-tap-vsock/releases/download/v0.5.0/gvproxy-linux
          sudo apt install podman
          sudo chmod 755 gvproxy
          sudo mv gvproxy-linux /usr/libexec/podman/gvproxy
    - run:
        name: Setup Podman
        command: |
          podman machine init --cpus 4 --memory 16384 --disk-size 80
          podman machine start
    - run:
        name: Check status of podman
        command: |
          podman ps
          podman images
