jobs:
  create-local-cluster:
    executor: redhat-openshift/machine-for-local-cluster
    steps:
    - redhat-openshift/create-local-cluster-with-oc:
        skip-registry-check: true
    - redhat-openshift/login-and-update-kubeconfig:
        insecure-skip-tls-verify: true
        openshift-platform-version: 4.x
        password: password
        server-address: 'https://127.0.0.1:8443'
        username: dev1
    - run:
        command: |
          oc status
          oc get ns
        name: Test the cluster
orbs:
  redhat-openshift: circleci/redhat-openshift@0.2.0
version: 2.1
workflows:
  deployment:
    jobs:
    - create-local-cluster
