version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: large
    steps:
    - checkout
    - run:
        name: Check CPU
        command: |
          lscpu
    - run:
        name: Check memory
        command: free -g
    - run:
        name: Install podman
        command: |
          echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
          curl -L "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/Release.key" | sudo apt-key add -
          sudo apt-get update
          sudo apt-get -y upgrade
          sudo apt-get -y install podman
    - run:
        name: Setup Podman
        command: |
          podman machine init --cpus 4 --memory 16384 --disk-size 80
          podman machine start
    - run:
        name: Check status of podman
        command: |
          podman ps
          podman images
