version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: xlarge
    steps:
    - checkout
    - run:
        name: Check CPU
        command: |
          lscpu
    - run:
        name: Check memory
        command: free -g
