name: CI test

# on:
#   workflow_run:
#     workflows: ["CI build"]
#     types:
#     - completed

# For debugging the pipeline
on:
  push:
    branches: [implement-ci-review]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      KUBECONFIG: kubeconfig
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: List files in the directory
      run: |
        ls ${{ github.workplace }}
    - name: Print CWD
      run: echo "$PWD"
    - name: Configure env
      run: |
        sudo apt-get update
        sudo apt-get install \
            ca-certificates \
            curl \
            wget \
            gnupg \
            lsb-release
        sudo mkdir -m 0755 -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo chmod a+r /etc/apt/keyrings/docker.gpg
        sudo apt-get update
    - name: Install Docker
      run: |
        sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    - name: Check docker is running
      run: |
        sudo systemctl status docker
    - name: Get Docker info
      run: |
        docker info
    - name: Get OC CLI Binary
      run: |
        wget https://github.com/okd-project/okd/releases/download/4.12.0-0.okd-2023-02-18-033438/openshift-client-linux-4.12.0-0.okd-2023-02-18-033438.tar.gz
        tar xzvf openshift-client-linux-4.12.0-0.okd-2023-02-18-033438.tar.gz
        sudo mv oc kubectl /usr/local/bin
    - name: Run OC Binary
      run: oc --help
    - name: Spin up microshift container
      run: |
        docker run -d --name microshift --privileged -v microshift-data:/var/lib -p 6443:6443 -p 80:80 -p 443:443 quay.io/microshift/microshift-aio:latest
        sleep 60s
    - name: Export the kubeconfig
      run: docker exec -i microshift cat /var/lib/microshift/resources/kubeadmin/kubeconfig > tests/kubeconfig
    - name: List the kubeconfig file
      run: ls tests
    - name: Run test script
      run: |
        cd tests
        sleep 30s
        ./ci_test.sh
